config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "authors#index"

  get "/authors", to: "authors#index"
  get "/books", to: "books#index"

  resources :authors do
    resources :books
  end

  resources :books #do
  #resources :authors
  #end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, dependent: :destroy

  validates :name, presence: true
  validates :bio, presence: true, length: { minimum: 10 }
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
    @books = @author.books
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to @author
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])

    if @author.update(author_params)
      redirect_to @author
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    redirect_to root_path, status: :see_other
  end

  private
  def author_params
    params.require(:author).permit(:name, :bio)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    @author = Author.find(@book.author_id)
  end

  def new
    @book = Book.new
  end

  def create
    @author = Author.find(params[:author_id])
    @book = @author.books.create(book_params)
    redirect_to author_path(@author)
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      redirect_to @book
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @author = Author.find(@book.author_id)

    @book.destroy
    redirect_to author_path(@author), status: :see_other
  end

  private
  def book_params
    params.require(:book).permit(:title, :synopsis)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/_author.html.erb
<p>
  <strong>Name:</strong>
  <%= author.name %>
<br>
  <strong>Bio:</strong>
  <%= author.bio %>
</p>

app/views/authors/_form.html.erb
<%= form_with model: author do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% author.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </p>

  <p>
    <%= form.label :bio %><br>
    <%= form.text_area :bio %><br>
    <% author.errors.full_messages_for(:bio).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/authors/edit.html.erb
<h1>Edit Author</h1>

<%= render "form", author: @author %>

app/views/authors/index.html.erb
<h1>Authors</h1>

<ul>
  <% @authors.each do |author| %>
    <li>
      <%= link_to author.name, author %>
    </li>
  <% end %>
</ul>

<li><%= link_to "New Author", new_author_path %></li>

<li><%= link_to "Books", books_path %></li>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render "form", author: @author %>

<li><%= link_to "Home", root_path %></li>

app/views/authors/show.html.erb
<h1><%= @author.name %></h1>

<p><%= @author.bio %></p>

<ul>
  <li><%= link_to "Edit Author", edit_author_path(@author) %></li>
  <li><%= link_to "Delete Author", author_path(@author), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  } %></li>
</ul>

<h2>Books</h2>

<ul>
  <% @books.each do |book| %>
    <li>
      <%= link_to book.title, book %>
    </li>
  <% end %>
</ul>

<h2>Add a book:</h2>
<%= form_with model: [ @author, @author.books.build ] do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :synopsis %><br>
    <%= form.text_area :synopsis %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>
<%#= render 'books/form' %>

<li><%= link_to "Authors", root_path %></li>
<li><%= link_to "Books", books_path %></li>

app/views/books/_book.html.erb
<p>
  <strong>Title:</strong>
  <%= book.title %>
<br>
  <strong>Synopsis:</strong>
  <%= book.synopsis %>
</p>

app/views/books/_form.html.erb
<%#= form_with model: [ @author, @author.books.build ] do |form| %>
<%= form_with model: book do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :synopsis %><br>
    <%= form.text_area :synopsis %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= render "form", book: @book %>

app/views/books/index.html.erb
<h1>Books</h1>

<ul>
  <% @books.each do |book| %>
    <li>
      <%= link_to book.title, book %>
    </li>
  <% end %>
</ul>

<li><%= link_to "Authors", root_path %></li>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render "form", book: @book %>

<li><%= link_to "Home", root_path %></li>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>

<p><%= @book.synopsis %></p>

<ul>
  <%= link_to "Edit Book", edit_book_path(@book) %>
  <li><%= link_to "Delete Book", book_path(@book), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  } %></li>
</ul>

<h1><%= link_to @author.name, @author %></h1>

<p><%= @author.bio %></p>

<li><%= link_to "Authors", root_path %></li>
<li><%= link_to "Books", books_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAppTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>